/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Component;

/**
 *
 * @author Harsha
 */
public class DashBoardItemInOut extends javax.swing.JPanel {

    /**
     * Creates new form DashBoardItemInOut
     */
    public DashBoardItemInOut() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shadowPanelSalesInv = new NEW.ShadowPanelOriginal();
        txtSalesExTaxTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtSalesExTaxAmount = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtSalesExTaxAmount1 = new javax.swing.JLabel();
        txtSalesExTaxAmount2 = new javax.swing.JLabel();
        txtSalesExTaxGrowthPercentage1 = new javax.swing.JLabel();
        txtSalesExTaxGrowthPercentage2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        shadowPanelSalesInv.setBackground(new java.awt.Color(255, 255, 255));
        shadowPanelSalesInv.setBorderRadius(10);
        shadowPanelSalesInv.setOpaque(true);
        shadowPanelSalesInv.setPreferredSize(new java.awt.Dimension(100, 100));
        shadowPanelSalesInv.setShadowDeep(0.1F);
        shadowPanelSalesInv.setShadowSize(8);

        txtSalesExTaxTitle.setBackground(new java.awt.Color(250, 251, 252));
        txtSalesExTaxTitle.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtSalesExTaxTitle.setForeground(new java.awt.Color(98, 99, 99));
        txtSalesExTaxTitle.setText("Attendance Count");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtSalesExTaxAmount.setBackground(new java.awt.Color(236, 236, 236));
        txtSalesExTaxAmount.setFont(new java.awt.Font("Roboto", 1, 40)); // NOI18N
        txtSalesExTaxAmount.setForeground(new java.awt.Color(124, 124, 124));
        txtSalesExTaxAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSalesExTaxAmount.setText("25");
        txtSalesExTaxAmount.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        txtSalesExTaxAmount.setPreferredSize(new java.awt.Dimension(20, 17));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtSalesExTaxAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSalesExTaxAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtSalesExTaxAmount1.setBackground(new java.awt.Color(236, 236, 236));
        txtSalesExTaxAmount1.setFont(new java.awt.Font("Roboto", 0, 30)); // NOI18N
        txtSalesExTaxAmount1.setForeground(new java.awt.Color(132, 187, 192));
        txtSalesExTaxAmount1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtSalesExTaxAmount1.setText("0");
        txtSalesExTaxAmount1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        txtSalesExTaxAmount1.setPreferredSize(new java.awt.Dimension(20, 17));

        txtSalesExTaxAmount2.setBackground(new java.awt.Color(236, 236, 236));
        txtSalesExTaxAmount2.setFont(new java.awt.Font("Roboto", 0, 30)); // NOI18N
        txtSalesExTaxAmount2.setForeground(new java.awt.Color(191, 164, 213));
        txtSalesExTaxAmount2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtSalesExTaxAmount2.setText("0");
        txtSalesExTaxAmount2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        txtSalesExTaxAmount2.setPreferredSize(new java.awt.Dimension(20, 17));

        txtSalesExTaxGrowthPercentage1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtSalesExTaxGrowthPercentage1.setForeground(new java.awt.Color(132, 187, 192));
        txtSalesExTaxGrowthPercentage1.setText("Permanent");
        txtSalesExTaxGrowthPercentage1.setIconTextGap(2);

        txtSalesExTaxGrowthPercentage2.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtSalesExTaxGrowthPercentage2.setForeground(new java.awt.Color(191, 164, 213));
        txtSalesExTaxGrowthPercentage2.setText("Non-Permanent");
        txtSalesExTaxGrowthPercentage2.setIconTextGap(2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSalesExTaxAmount1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(txtSalesExTaxAmount2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSalesExTaxGrowthPercentage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSalesExTaxGrowthPercentage2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSalesExTaxAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalesExTaxGrowthPercentage1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSalesExTaxAmount2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalesExTaxGrowthPercentage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtSalesExTaxGrowthPercentage1, txtSalesExTaxGrowthPercentage2});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtSalesExTaxAmount1, txtSalesExTaxAmount2});

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout shadowPanelSalesInvLayout = new javax.swing.GroupLayout(shadowPanelSalesInv);
        shadowPanelSalesInv.setLayout(shadowPanelSalesInvLayout);
        shadowPanelSalesInvLayout.setHorizontalGroup(
            shadowPanelSalesInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shadowPanelSalesInvLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(shadowPanelSalesInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSalesExTaxTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(shadowPanelSalesInvLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addContainerGap())
        );
        shadowPanelSalesInvLayout.setVerticalGroup(
            shadowPanelSalesInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shadowPanelSalesInvLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSalesExTaxTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(shadowPanelSalesInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(shadowPanelSalesInv, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private NEW.ShadowPanelOriginal shadowPanelSalesInv;
    private static javax.swing.JLabel txtSalesExTaxAmount;
    private static javax.swing.JLabel txtSalesExTaxAmount1;
    private static javax.swing.JLabel txtSalesExTaxAmount2;
    private javax.swing.JLabel txtSalesExTaxGrowthPercentage1;
    private javax.swing.JLabel txtSalesExTaxGrowthPercentage2;
    private javax.swing.JLabel txtSalesExTaxTitle;
    // End of variables declaration//GEN-END:variables
}
