/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import com.formdev.flatlaf.FlatLightLaf;
import config.SystemSettings;
import database.DatabaseConnection;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Harsha
 */
public class Splash extends javax.swing.JFrame {
public static MainFrame f1;

    /**
     * Creates new form Splash
     */
    public Splash() {
        initComponents();
        btnError.setVisible(false);
        btnClose.setVisible(false);
        
        this.getRootPane().setOpaque(false);
        this.getContentPane().setBackground(new Color(0, 0, 0, 0));
        this.setBackground(new Color(0, 0, 0, 0));
        
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png")).getImage());
        setLocationRelativeTo(null);
        
        Start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        btnError = new javax.swing.JButton();
        jlLoadText1 = new javax.swing.JLabel();
        jlLoadText = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        btnClose.setBackground(new java.awt.Color(27, 20, 79));
        btnClose.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnClose.setForeground(new java.awt.Color(188, 176, 238));
        btnClose.setText("X");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose);
        btnClose.setBounds(485, 20, 20, 21);

        btnError.setBackground(new java.awt.Color(34, 26, 92));
        btnError.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnError.setForeground(new java.awt.Color(242, 242, 242));
        btnError.setText("Show Error");
        btnError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnErrorActionPerformed(evt);
            }
        });
        jPanel1.add(btnError);
        btnError.setBounds(50, 240, 90, 21);

        jlLoadText1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jlLoadText1.setForeground(new java.awt.Color(134, 159, 203));
        jlLoadText1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlLoadText1.setText("Version 1.0.2.0");
        jlLoadText1.setRequestFocusEnabled(false);
        jPanel1.add(jlLoadText1);
        jlLoadText1.setBounds(360, 150, 110, 20);

        jlLoadText.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jlLoadText.setForeground(new java.awt.Color(204, 204, 204));
        jlLoadText.setText("Loading....");
        jPanel1.add(jlLoadText);
        jlLoadText.setBounds(50, 270, 210, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/splash.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 540, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnErrorActionPerformed
        JOptionPane.showMessageDialog(this, "Error: \n" + DatabaseConnection.ErrorMsg, "Database Connection", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnErrorActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e) {
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash().setVisible(true);
            }
        });
    }
    
    
    
    private void Start(){
        
        new Thread(new Runnable() {
            @Override
            public void run() {
                jlLoadText1.setText(SystemSettings.Version_Number);
                 for (int x = 0; x < 601; x = x + 5) {
                     try {
                         Thread.sleep(5);

                        if (x == 10) {
                            jlLoadText.setText("Initializing JRE...");
                            // getMysqlPath();
                            Thread.sleep(300);
                        }
                        
                        if(x==200){
                            Thread.sleep(300);
                            btnClose.setVisible(true);
                            if(DatabaseConnection.Connect() == null){
                                btnError.setVisible(true);
                                jlLoadText.setText("Database Connection Error.");
                                return;
                            }
                            btnClose.setVisible(false);
                            //DatabaseConnection.Connect();
                        }
                        
                        if (x == 250) {

                            jlLoadText.setText("Initializing ui...");

                            f1 = new MainFrame();
                            Thread.sleep(200);

                            jlLoadText.setText("Done loading.");
                        }
                        
                         if (x == 350) {

                            jlLoadText.setText("Starting...");

                            Thread.sleep(200);
                            f1.setVisible(true);
                            dispose();

                        }
                        
                        
                     } catch (Exception e) {
                     }
                 }
            }
        }).start();
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnError;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlLoadText;
    private javax.swing.JLabel jlLoadText1;
    // End of variables declaration//GEN-END:variables
}
